baseURL = "https://example.com"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
defaultContentLanguage = "de"
enableEmoji = true
hasCJKLanguage = false
languageCode = "de-de"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
theme = "hermit"
title = "yourmet"
[author]
name = "Timo Traulsen"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "About"
url = "/about-hugo/"
weight = 2
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1
[params]
dateform = "2 Jan, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "2 Jan"
footerCopyright = " &#183; <a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
homeSubtitle = "meet. eat. deplete."
justifyContent = false
[[params.social]]
name = "twitter"
url = "https://twitter.com/"
[[params.social]]
name = "instagram"
url = "https://instagram.com/"
[[params.social]]
name = "github"
url = "https://github.com/"
[taxonomies]
category = ""
tag = "tags"
